#!/bin/bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
## Kitty ##
rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

## Tmux ##
rm -rf $HOME/.tmux.conf
ln -s  $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

## t scripts ##
mkdir -p $HOME/.local/bin
rm -rf $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t

## nvim ##
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

## i3 ##
rm -rf $HOME/.config/i3/config
ln -s $DOTFILES/i3/config $HOME/.config/i3/config
rm -rf $HOME/.config/i3blocks/config
ln -s $DOTFILES/i3/i3blocks.conf $HOME/.config/i3blocks/config
